name: "helyo"
baseurl: ""

language: "en"
timezone: "Europe/Paris"
encoding: "utf-8"

gems: [jekyll-paginate]
paginate: 10
excerpt_separator: "---"

exclude: ["node_modules"]

markdown: kramdown
highlighter: rouge

sass:
  style: compressed

kramdown:
  auto_ids: true
  auto_id_stripping: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
